name: Build Android App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Flutter Android APK
    runs-on: ubuntu-latest
    steps:
      # 1. تنزيل كود المشروع
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      # 2. إعداد بيئة جافا
      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. تثبيت بيئة Flutter
      - name: 💙 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. تثبيت مكاتب وحزم Flutter
      - name: 📦 Install Flutter Dependencies
        run: flutter pub get

      # 5. بناء ملف APK الإنتاجي
      - name: 🔨 Build Android Release APK
        run: flutter build apk --release

      # 6. رفع ملف الـ APK لتتمكن من تحميله من GitHub
      - name: 🚀 Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: App-Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 14
